### ISSUE TITLE
Working with Nextcloud plugin?

### ISSUE THREAD

**Issue by poVoq** [Kurounin/ep_auth_session#2]
Am I guessing right that this would solve one of the issues with the Nextcloud plugin, as outlined here:
https://github.com/otetard/ownpad/issues/4

Would be really nice if someone with Etherpad coding experience could have a look that Ownpad's API integration branch...

**Comment by Kurounin** [comment]
I'm not familiar with **OwnPad** or **NextCloud**. I created this plugin because after authenticating through the **Etherpad API** I still needed a way to set the session cookie before accessing any protected links from **Etherpad**.
Regarding that [branch](https://github.com/otetard/ownpad/blob/feature/etherpad-api/TODO.md), after adding this plugin to the **Etherpad instance**, you would need to modify on this line https://github.com/otetard/ownpad/blob/290e5e40f184f71edcbb5a43dec35a99cf962280/controller/displaycontroller.php#L104 to add `sessionID=SESSION_ID`, using the available `$session->sessionID`, instead of creating the cookie yourself (which doesn't work if it's on a different domain). This could be done based on a **OwnPad** setting.
